name: Project is testable

on: [push]

jobs:
    tests:
        name: Testing project
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [15.x]
                # node-version: [13.x, 14.x, 15.x]
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Install all dependencies
              run: npm install
            - name: Lint the source code
              run: npm run lint
