name: Project is testable

on: [push]

jobs:
  tests:
    name: Testing project
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [13.x, 14.x, 15.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install all dependencies
        run: npm install
      - name: Lint the source code
        run: npm run lint

  deploy:
    name: Deploying the project to Github pages
    runs-on: ubuntu-latest
    needs: [tests]
    if: "contains(github.ref, 'main')"
    steps:
      - name: Check out the code
        uses: actions/checkout@v2
      - name: Use Node.js 15.x
        uses: actions/setup-node@v1
        with:
          node-version: 15.x
      - name: Install all dependencies
        run: npm install
      - name: Build the source code
        run: npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
